### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by tapdiego-amzn** [XuSihan/LiDetector#1]
Thank you for research in this area and for this project. I noticed this project seems to have no license attached to it — can you please clarify the licensing terms, ideally by adding a project license? It would also be great if you could to the same for your datasets at https://sites.google.com/view/lidetector.

**Comment by XuSihan** [comment]
@tapdiego-amzn Thank you for reminding us of the issues. We will add a project license and clarify some licensing terms.

**Comment by tapdiego-amzn** [comment]
This seems fixed now with the addition of https://github.com/XuSihan/LiDetector/blob/main/LICENSE — thank you!
