### ISSUE TITLE
why  library_license  in  extract_licenseRelated_fromPros.py is {} ?

### ISSUE THREAD

**Issue by ghost** [XuSihan/LiDetector#2]
why  ```library_license```  in  ```extract_licenseRelated_fromPros.py``` is {} ? So if  I want to get the licenses of third-party libriaries, how can I do? I check the whole repo, and do not find how the ```library_license ``` is generated.

**Comment by ghost** [comment]
I would be very grateful if you could answer this for me!

**Comment by ghost** [comment]
@Ashley123456789 @XuSihan

**Comment by Ashley123456789** [comment]
Thanks, the `library_license` dictionary is generated by reading _library_license.txt_ in `main` function of `extract_licenseRelated_fromPros.py`
