### ISSUE TITLE
what is the file named `dwavesystems__dwave-ocean-sdk__declared-license-1.txt` in `/model/DetermAtti/checked-repos-list___.txt`

### ISSUE THREAD

**Issue by BodyCSoulN** [XuSihan/LiDetector#4]
Hi,

I am trying to run `model/DetermAtti/get_treeAtti.py`.

But there was an error:`'no such file or directory:..\\LocateTerms\\data\\test-pre\\dwavesystems__dwave-ocean-sdk__declared-license-1.txt`

I found that this name comes from the file 'checked-repos-list___.txt'. What is the usage of this file? And how can I get it?

Thanks
@XuSihan @Ashley123456789

**Comment by Ashley123456789** [comment]
You can run `model\PreprocessData\cleanData_intoTestDir.py` first, and the file `checked-repos-list___.txt` will be generated.

**Comment by Ashley123456789** [comment]
Run the python scripts according the order below:
```
extract_licenseRelated_fromPros.py
collect_files_for_model.py
model\PreprocessData\cleanData_intoTestDir.py
model\LocateTerms\ner_predict.py
model\DetermAtti\get_treeAtti.py
```
These files like `XXXX__declared-license-1.txt` are generated in the preprocessing step.

**Comment by BodyCSoulN** [comment]
And what is `//output/finished_pac_list.txt`?

**Comment by BodyCSoulN** [comment]
And what is `finished_pac_list.txt` and `ex_pac_list.txt`?

**Comment by BodyCSoulN** [comment]
if I only want the result of `get_treeAtti.py`, what should I do? what files I need?
@Ashley123456789 @XuSihan
